# Generated by Django 5.0.2 on 2024-03-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_gutenberg_id', models.IntegerField()),
                ('text', models.TextField()),
                ('rel_i', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
