# Generated by Django 5.0.2 on 2024-03-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='book_builder_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chunk',
            name='rel_i',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
