# Generated by Django 5.0.2 on 2024-03-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg', '0003_book_lemma_vocabulary_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='gutenberg_id',
            field=models.IntegerField(unique=True),
        ),
    ]
