# Generated by Django 5.0.2 on 2024-03-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg', '0004_alter_book_gutenberg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
