# Generated by Django 5.0.2 on 2024-03-13 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg', '0009_delete_vocabulary_chunk_vocab_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='book_gutenberg_id',
        ),
        migrations.AddField(
            model_name='chunk',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='gutenberg.book'),
            preserve_default=False,
        ),
    ]
