# Generated by Django 5.0.2 on 2024-03-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg', '0010_remove_chunk_book_gutenberg_id_chunk_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
