# Generated by Django 5.0.2 on 2024-04-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg', '0011_chunk_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='rel_i',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
