# Generated by Django 5.0.2 on 2024-04-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg', '0012_remove_chunk_rel_i_book_author_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='stem',
            field=models.TextField(null=True),
        ),
    ]
