# Generated by Django 5.0.2 on 2024-04-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg', '0013_lemma_stem'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='stem',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
